<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>turbo</string>
	</array>
	<key>name</key>
	<string>TurboScript</string>
	<key>scopeName</key>
	<string>source.turbo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#normal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>normal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>

				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>

				<dict>
					<key>include</key>
					<string>#parentheses</string>
				</dict>

				<dict>
					<key>name</key>
					<string>comment.turbo</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>

				<dict>
					<key>name</key>
					<string>comment.turbo</string>
					<key>match</key>
					<string>//.*</string>
				</dict>

				<dict>
					<key>name</key>
					<string>constant.numeric.turbo</string>
					<key>match</key>
					<string>\b\d+\b</string>
				</dict>

				<dict>
					<key>name</key>
					<string>constant.language.turbo</string>
					<key>match</key>
					<string>\b(?:false|null|true)\b</string>
				</dict>

				<dict>
					<key>begin</key>
					<string>\b(class|interface)(?:\s+([A-Za-z$_][\w$]*)\b)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.turbo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.turbo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>end</key>
							<string>(?=\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>name</key>
									<string>keyword.turbo</string>
									<key>match</key>
									<string>\b(get|set)\b\s+(?=\w)</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#symbols</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>

				<dict>
					<key>begin</key>
					<string>\b(enum)(?:\s+([A-Za-z$_][\w$]*)\b)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.turbo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.turbo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>end</key>
							<string>(?=\})</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#normal</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>

				<dict>
					<key>match</key>
					<string>\.\w+\b</string>
				</dict>

				<dict>
					<key>begin</key>
					<string>\b(const|let|var)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.turbo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#symbols</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>begin</key>
					<string>\b(function)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.turbo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[\{;])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#symbols</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>name</key>
					<string>keyword.turbo</string>
					<key>match</key>
					<string>#(?:define|elif|else|endif|error|if|undef|warning)\b</string>
				</dict>

				<dict>
					<key>name</key>
					<string>keyword.turbo</string>
					<key>match</key>
					<string>\b(?:alignof|as|break|class|const|continue|declare|else|enum|export|extends|extern|function|if|implements|import|interface|let|new|operator|private|protected|public|return|sizeof|static|unsafe|var|while)\b</string>
				</dict>

				<dict>
					<key>name</key>
					<string>invalid.turbo</string>
					<key>match</key>
					<string>[\}\]\)]</string>
				</dict>

				<dict>
					<key>name</key>
					<string>string.quoted.turbo</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>["\n]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>name</key>
					<string>string.quoted.turbo</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>['\n]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>name</key>
					<string>string.quoted.turbo</string>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

		<key>symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.function.turbo</string>
					<key>match</key>
					<string>\b([A-Za-z$_][\w$]*)\b</string>
				</dict>

				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#normal</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>(?=[=,;{)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>begin</key>
					<string>=</string>
					<key>end</key>
					<string>(?=[,;)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#normal</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[A-Za-z$_][\w$]*\b</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#symbols</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
			</array>
		</dict>

		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.turbo</string>
					<key>match</key>
					<string>\b[A-Za-z$_][\w$]*\b</string>
				</dict>

				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
			</array>
		</dict>

		<key>braces</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
			</array>
		</dict>

		<key>brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
			</array>
		</dict>

		<key>parentheses</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
